properties([
	parameters([
    stringParam(
      defaultValue: 'SlaveUI1',
      description: 'Node name to run the job',
      name: 'NodeName',
    ),
	  stringParam(
			defaultValue: 'http://clm-aus-t5jj96.bmc.com:8008',
			description: 'Execution Stack',
      name: 'BaseUrl',
    ),
    stringParam(
      defaultValue: 'Regression:UI:Auto:Upgrade',
      description: 'Jira test cycle',
      name: 'CycleName',
    ),
    stringParam(
      defaultValue: 'UI_Auto:Upgrade_Protractor',
      description: 'Jira test cycle folder',
      name: 'FolderName',
    ),
    booleanParam(
      defaultValue: false,
      description: 'Pass Percent',
      name: 'Stats'
    )
  ])
])

node("${NodeName}"){
  stage('Clone Sources') {
    git branch: 'master',
    credentialsId: '807c8e4d-6d6c-47e1-a62e-ef2de91d6dce',
    url: 'https://github.bmc.com/DSM-Apps/bwf-e2e-protractor.git'
  }

  stage('Build') {
    bat "IF EXIST e2e\\reports RMDIR /S /Q e2e\\reports"
    bat "npm install"
    bat "npm run webdriver-update"
  }

  try {
    stage('Run Automation') {
      bat "npm run e2e-protractor -- --baseUrl=%BaseUrl%"
    }
  } catch (Exception e) {
    echo "Automation Run Failed"
  }

  try {
    stage('Create Jira Cycle') {
      bat "npm run jira-cycle -- --cycle=%CycleName% --folder=%FolderName% --stats=%Stats%"
    }
  } catch (Exception e) {
    echo "Create Jira Cycle Failed"
  }

  try {
    stage('Send Email'){
      emailext (
        subject: "BWF UI - Protractor Automation Report Build # ${env.BUILD_NUMBER}",
        body:
          """
          <style type="text/css">
            body {
              margin: 0px;
              padding: 15px;
              font-family: "Lucida Sans Unicode";
              font-size: 10pt;
            }
            h3 {
              background: #F2B66B;
              padding: 10px;
              border: 1px solid #333;
            }
            table {
              width: 70%;
            }
            td.bold {
              width: 30%;
              font-weight:bold;
            }
            table, tr, td {
              border: 1px solid black;
              border-collapse: collapse;
              padding: 5px;
            }
          </style>
          <h3>BWF UI - Protractor Automation Report</h3>
          <table>
            <tr><td class=bold>Environment Name: </td><td>${env.BaseUrl}</td></tr>
            <tr><td class=bold>Build URL:</td><td><a href="${env.BUILD_URL}">View Jenkins</a></td></tr>
            <tr><td class=bold>Build Artefact:</td><td><a href="ftp://vl-pun-rem-qa4n/punebuild/automation-results/protractor-result/UIAutoRun_Build${env.BUILD_NUMBER}">FTP Link</a></td></tr>
          """
          +
          '${FILE, path="e2e/reports/spec-jira-report/CycleReport.html"}'
          +
          "</table>",
        to: "prasad_vidhate@bmc.com;sunil_patil@bmc.com;pravin_ajagunde@bmc.com;tushar_garud@bmc.com;anant_sahitya@bmc.com;swapnil_khobragade_tp@bmc.com;ankush_agrawal_tp@bmc.com;pravin_tidke_tp@bmc.com;kiran_gaikwad_tp@bmc.com;naziya_mujawar@bmc.com;rahul_dhiman_tp@bmc.com;rajan_bangar_tp@bmc.com;apurva_deshmukh_tp@bmc.com;ashish_gabhane@bmc.com;swapnil_yelkar@bmc.com;sushrut_sawarkar@bmc.com",
        from: "jenkins@noreply",
        attachmentsPattern: '**/*jira-report.csv'
      )
    }
  } catch (Exception e) {
    echo "Send Email Failed"  
  }

  try {
    stage('Upload Over FTP'){
      echo "ZIP"
      zip archive: false, dir: 'e2e/reports', zipFile: 'e2e/reports/reports.zip'
      echo "END - ZIP"
      ftpPublisher alwaysPublishFromMaster: true, continueOnError: true, failOnError: false, publishers: [
        [configName: 'vl-pun-rem-qa4n-protractor', transfers: [
          [asciiMode: false, cleanRemote: false, excludes: '', flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: "UIAutoRun_Build${env.BUILD_NUMBER}", remoteDirectorySDF: false, removePrefix: '', sourceFiles: 'e2e/reports/reports.zip']
        ], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: true]
      ]
    }
  } catch (Exception e) {
    echo "FTP Upload Failed"
  }
}
